using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace stadiumSeating
{
    public partial class stadiumSeating : Form
    {
        public stadiumSeating()
        {
            InitializeComponent();
        }

        private void calculateButton_Click(object sender, EventArgs e)
        {
            try
            {
                //Constants:
                const double aPrice = 15; //to hold the price of class A tickets
                const double bPrice = 12; //to hold the price of class B tickets
                const double cPrice = 9;  //to hold the price of class C tickets

                //Variables:
                double classASold;        //to hold the number of tickets sold in class A
                double classBSold;        //to hold the number of tickets sold in class B
                double classCSold;       //to hold the number of tickets sold in class C
                double aRevenue;         //to hold the revenue generated by class A 
                double bRevenue;        //to hold the revenue generated by class B
                double cRevenue;        //to hold the revenue generated by class C
                double totalRevenue;   //to hold the total revenue generated

                //Initializations:
                classASold = double.Parse(inputATextBox.Text);
                classBSold = double.Parse(inputBTextBox.Text);
                classCSold = double.Parse(inputCTextBox.Text);

                //Calculations:
                aRevenue = classASold * aPrice;
                bRevenue = classBSold * bPrice;
                cRevenue = classCSold * cPrice;
                totalRevenue = aRevenue + bRevenue + cRevenue;

                //Display output to the appropiate Labels:
                displayAOutputLabel.Text = aRevenue.ToString("c");
                displayBOutputLabel.Text = bRevenue.ToString("c");
                displayCOutputLabel.Text = cRevenue.ToString("c");
                displayTotalOutputLabel.Text = totalRevenue.ToString("c");

            }
            catch(Exception ex)
            {
                //Display the default error message.
                MessageBox.Show(ex.Message);
            }
        }

        private void clearButton_Click(object sender, EventArgs e)
        {
            //Clear TextBox controls.
            inputATextBox.Text = "";
            inputBTextBox.Text = "";
            inputCTextBox.Text = "";

            //Clear the output Labels.
            displayAOutputLabel.Text = "";
            displayBOutputLabel.Text = "";
            displayCOutputLabel.Text = "";
            displayTotalOutputLabel.Text = "";

            //Set the focus to inputATextBox.
            inputATextBox.Focus();
        }

        private void exitButton_Click(object sender, EventArgs e)
        {
            //Verify that the user wants to exit the program.
            if (MessageBox.Show("Are You Sure To Exit?", "Exit", MessageBoxButtons.OKCancel) == DialogResult.OK)
            {
                Application.Exit();
            }
        }
    }
}
